### ISSUE TITLE
feat: it is not clear that Tracim address with protocol (http// / https://) are not accepted

### ISSUE THREAD

**Issue by yvan-algoo** [buxx/trsync-manager-configure#1]
When trying to add a Tracim server, if you enter an address prefixed with the protocol (http:// or https://), the following error is displayed (translated from French): `Address error or no connection`

Ideally, it could automatically strip the prefix.

Thanks,
Yvan

**Comment by buxx** [comment]
@yvan-algoo This repository is obsolete. Configuration window is included in trsync repository. I close the issue and archive the repository !
